# Generated by Django 6.1.1 on 2026-09-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(help_text='OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(blank=True, choices=[('place', 'Place exact'), ('place_suffix', 'Place, suffix stripped'), ('place_nospace', 'Place, spaces ignored')], max_length=20, null=True)),
                ('imported_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('population', models.PositiveIntegerField(default=0)),
                ('name_norm', models.CharField(max_length=200)),
                ('name_nospace', models.CharField(max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'name_norm'], name='routing_pla_state_020488_idx'), models.Index(fields=['state', 'name_nospace'], name='routing_pla_state_8a95df_idx')],
            },
        ),
    ]
